### ISSUE TITLE
Soldering Iron Firmware Missing

### ISSUE THREAD

**Issue by guyf2010** [RiS3-Lab/p2im-real_firmware#2]
I see that addition of the soldering iron firmware has been noted on the todo list; could this be released to support replicating your results and benchmarking of our fuzzer?

**Comment by dokodokoR** [comment]
@guyf2010 
You can get the src of soldering iron from [here](https://github.com/Ralim/IronOS).

However, you need to invoke `aflCall` .

**Comment by guyf2010** [comment]
@dokodokoR 
Thanks, I did see there was a link referencing the original firmware in the paper, but I don't believe the version used was stated in the paper, nor did I want to influence results by selecting a different point to call aflCall than that used in the paper.

**Comment by dokodokoR** [comment]
@guyf2010 
I would also like to have the firmware binary used in the paper, but it doesn't seem to be available yet...

**Comment by bofeng17** [comment]
The soldering iron binary used in the paper is attached.
[TS100_EN.elf.zip](https://github.com/RiS3-Lab/p2im-real_firmware/files/7533092/TS100_EN.elf.zip)

**Comment by guyf2010** [comment]
Thanks,

Is it possible to have this added to the repository with the source code for those looking for it in future?

**Comment by bofeng17** [comment]
I'd like to but I forgot which commit of the original firmware I tested in the paper.
